=== doubleencore/QaTool/sample_schema1/r/r011/standings.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Standings",
    "definitions": {
        "Standings": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "_debug": {
                    "$ref": "#/definitions/Debug"
                },
                "standings_title": {
                    "type": "string"
                },
                "standings_point_title": {
                    "type": "string"
                },
                "thru_tournament_name": {
                    "type": "string"
                },
                "thru_tournament_date": {
                    "type": "string",
                    "format": "date"
                },
                "round_status": {
                    "type": "string"
                },
                "last_updated": {
                    "type": "string"
                },
                "player_count": {
                    "type": "string"
                },
                "standings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Standing"
                    }
                }
            },
            "required": [
                "_debug",
                "last_updated",
                "player_count",
                "round_status",
                "standings",
                "standings_point_title",
                "standings_title",
                "thru_tournament_date",
                "thru_tournament_name"
            ],
            "title": "Standings"
        },
        "Debug": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "primaryTid": {
                    "type": "string"
                },
                "statsFile": {
                    "type": "string"
                }
            },
            "required": [
                "primaryTid",
                "statsFile"
            ],
            "title": "Debug"
        },
        "Standing": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "pid": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "short_name": {
                    "type": "string"
                },
                "events_played": {
                    "type": "string"
                },
                "official_total_points": {
                    "type": "string"
                },
                "tour_wins": {
                    "$ref": "#/definitions/TourWINS"
                },
                "top_10_finishes": {
                    "$ref": "#/definitions/Top10_Finishes"
                },
                "points_behind_lead": {
                    "type": "string"
                },
                "official_rank": {
                    "type": "string"
                },
                "prev_rank": {
                    "type": "string"
                },
                "position_change": {
                    "type": "string"
                },
                "group": {
                    "type": "integer"
                },
                "projected_event_points": {
                    "type": "string"
                },
                "projected_rank": {
                    "type": "string"
                },
                "projected_total_points": {
                    "type": "string"
                },
                "projected_sort": {
                    "type": "integer"
                },
                "official_sort": {
                    "type": "integer"
                },
                "projected_group": {
                    "type": "integer"
                },
                "highlight": {
                    "type": "boolean"
                }
            },
            "required": [
                "events_played",
                "first_name",
                "group",
                "highlight",
                "last_name",
                "official_rank",
                "official_sort",
                "official_total_points",
                "pid",
                "points_behind_lead",
                "position_change",
                "prev_rank",
                "projected_event_points",
                "projected_group",
                "projected_rank",
                "projected_sort",
                "projected_total_points",
                "short_name",
                "top_10_finishes",
                "tour_wins"
            ],
            "title": "Standing"
        },
        "Top10_Finishes": {
            "type": "string",
            "enum": [
                "10",
                "11",
                "8",
                "7",
                "9",
                "6",
                "4",
                "5",
                "2",
                "3",
                "1",
                ""
            ],
            "title": "Top10_Finishes"
        },
        "TourWINS": {
            "type": "string",
            "enum": [
                "3",
                "5",
                "4",
                "1",
                ""
            ],
            "title": "TourWINS"
        }
    }
}

=== doubleencore/QaTool/sample_data/r/r011/standings2.json
{"_debug": {"primaryTid":"011","statsFile":"file:///opt/dataprocessing/repo/r/stats/2017/109.xml"},"standings_title": "Official Money","standings_point_title": "MONEY","thru_tournament_name": "Presidents Cup","thru_tournament_date": "2017-10-01","round_status": "UNK","last_updated": "2018-04-11T12:30-04:00","player_count": "262","standings": [{"pid": "33448","first_name": "Justin","last_name": "Thomas","short_name": "J","events_played": "25","official_total_points": "$9,921,560","tour_wins": "","top_10_finishes": "5","points_behind_lead": "","official_rank": "1","prev_rank": "1","position_change": "-2","group": 1,"projected_event_points": "3","projected_rank": "3","projected_total_points": "$4,468,855","projected_sort": 3,"official_sort": 1,"projected_group": 1,"highlight": false},{"pid": "34046","first_name": "Jordan","last_name": "Spieth","short_name": "J","events_played": "23","official_total_points": "$9,433,033","tour_wins": "","top_10_finishes": "3","points_behind_lead": "","official_rank": "2","prev_rank": "2","position_change": "-4","group": 1,"projected_event_points": "0","projected_rank": "6","projected_total_points": "$2,976,308","projected_sort": 6,"official_sort": 2,"projected_group": 1,"highlight": false},{"pid": "30925","first_name": "Dustin","last_name": "Johnson","short_name": "D","events_played": "20","official_total_points": "$8,732,193","tour_wins": "","top_10_finishes": "4","points_behind_lead": "","official_rank": "3","prev_rank": "3","position_change": "2","group": 1,"projected_event_points": "66","projected_rank": "1","projected_total_points": "$6,219,225","projected_sort": 1,"official_sort": 3,"projected_group": 1,"highlight": false},{"pid": "32839","first_name": "Hideki","last_name": "Matsuyama","short_name": "H","events_played": "22","official_total_points": "$8,380,570","tour_wins": "","top_10_finishes": "3","points_behind_lead": "","official_rank": "4","prev_rank": "4","position_change": "2","group": 1,"projected_event_points": "40","projected_rank": "2","projected_total_points": "$4,869,791","projected_sort": 2,"official_sort": 4,"projected_group": 1,"highlight": false},{"pid": "46970","first_name": "Jon","last_name": "Rahm","short_name": "J","events_played": "23","official_total_points": "$6,123,248","tour_wins": "","top_10_finishes": "1","points_behind_lead": "","official_rank": "5","prev_rank": "5","position_change": "1","group": 1,"projected_event_points": "3","projected_rank": "4","projected_total_points": "$3,976,615","projected_sort": 4,"official_sort": 5,"projected_group": 1,"highlight": false},{"pid": "32102","first_name": "Rickie","last_name": "Fowler","short_name": "R","events_played": "21","official_total_points": "$6,083,197","tour_wins": "","top_10_finishes": "1","points_behind_lead": "","official_rank": "6","prev_rank": "6","position_change": "-3","group": 1,"projected_event_points": "5","projected_rank": "9","projected_total_points": "$2,649,238","projected_sort": 9,"official_sort": 6,"projected_group": 1,"highlight": false},{"pid": "26851","first_name": "Marc","last_name": "Leishman","short_name": "M","events_played": "25","official_total_points": "$5,866,391","tour_wins": "","top_10_finishes": "2","points_behind_lead": "","official_rank": "7","prev_rank": "7","position_change": "-7","group": 1,"projected_event_points": "0","projected_rank": "14","projected_total_points": "$2,342,549","projected_sort": 14,"official_sort": 7,"projected_group": 1,"highlight": false},{"pid": "36689","first_name": "Brooks","last_name": "Koepka","short_name": "B","events_played": "24","official_total_points": "$5,612,397","tour_wins": "","top_10_finishes": "1","points_behind_lead": "","official_rank": "8","prev_rank": "8","position_change": "-8","group": 1,"projected_event_points": "54","projected_rank": "16","projected_total_points": "$2,207,025","projected_sort": 16,"official_sort": 8,"projected_group": 1,"highlight": false},{"pid": "29478","first_name": "Kevin","last_name": "Kisner","short_name": "K","events_played": "28","official_total_points": "$4,766,936","tour_wins": "","top_10_finishes": "1","points_behind_lead": "","official_rank": "9","prev_rank": "9","position_change": "-8","group": 1,"projected_event_points": "6","projected_rank": "17","projected_total_points": "$2,195,417","projected_sort": 17,"official_sort": 9,"projected_group": 1,"highlight": false},{"pid": "27644","first_name": "Brian","last_name": "Harman","short_name": "B","events_played": "30","official_total_points": "$4,396,470","tour_wins": "","top_10_finishes": "1","points_behind_lead": "","official_rank": "10","prev_rank": "10","position_change": "-1","group": 1,"projected_event_points": "7","projected_rank": "11","projected_total_points": "$2,537,788","projected_sort": 11,"official_sort": 10,"projected_group": 1,"highlight": false},{"pid": "24361","first_name": "Pat","last_name": "Perez","short_name": "P","events_played": "26","official_total_points": "$4,361,400","tour_wins": "","top_10_finishes": "1","points_behind_lead": "","official_rank": "11","prev_rank": "11","position_change": "6","group": 1,"projected_event_points": "40","projected_rank": "5","projected_total_points": "$3,469,475","projected_sort": 5,"official_sort": 11,"projected_group": 1,"highlight": false},{"pid": "48081","first_name": "Xander","last_name": "Schauffele","short_name": "X","events_played": "28","official_total_points": "$4,312,674","tour_wins": "","top_10_finishes": "2","points_behind_lead": "","official_rank": "12","prev_rank": "12","position_change": "-119","group": 1,"projected_event_points": "","projected_rank": "131","projected_total_points": "$377,067","projected_sort": 131,"official_sort": 12,"projected_group": 0,"highlight": false},{"pid": "40026","first_name": "Daniel","last_name": "Berger","short_name": "D","events_played": "26","official_total_points": "$4,287,161","tour_wins": "","top_10_finishes": "1","points_behind_lead": "","official_rank": "13","prev_rank": "13","position_change": "-13","group": 1,"projected_event_points": "4","projected_rank": "26","projected_total_points": "$1,742,734","projected_sort": 26,"official_sort": 13,"projected_group": 1,"highlight": false},{"pid": "23108","first_name": "Matt","last_name": "Kuchar","short_name": "M","events_played": "26","official_total_points": "$4,282,489","tour_wins": "","top_10_finishes": "","points_behind_lead": "","official_rank": "14","prev_rank": "14","position_change": "-36","group": 1,"projected_event_points": "2","projected_rank": "50","projected_total_points": "$1,197,950","projected_sort": 50,"official_sort": 14,"projected_group": 2,"highlight": false},{"pid": "22405","first_name": "Justin","last_name": "Rose","short_name": "J","events_played": "18","official_total_points": "$4,245,308","tour_wins": "","top_10_finishes": "","points_behind_lead": "","official_rank": "15","prev_rank": "15","position_change": "7","group": 1,"projected_event_points": "4","projected_rank": "8","projected_total_points": "$2,751,715","projected_sort": 8,"official_sort": 15,"projected_group": 1,"highlight": false},{"pid": "12716","first_name": "Charley","last_name": "Hoffman","short_name": "C","events_played": "31","official_total_points": "$4,161,008","tour_wins": "","top_10_finishes": "","points_behind_lead": "","official_rank": "16","prev_rank": "16","position_change": "-14","group": 1,"projected_event_points": "28","projected_rank": "30","projected_total_points": "$1,590,613","projected_sort": 30,"official_sort": 16,"projected_group": 1,"highlight": false},{"pid": "25364","first_name": "Paul","last_name": "Casey","short_name": "P","events_played": "24","official_total_points": "$3,906,974","tour_wins": "","top_10_finishes": "","points_behind_lead": "","official_rank": "17","prev_rank": "17","position_change": "-12","group": 1,"projected_event_points": "40","projected_rank": "29","projected_total_points": "$1,652,197","projected_sort": 29,"official_sort": 17,"projected_group": 1,"highlight": false},{"pid": "21209","first_name": "Sergio","last_name": "Garcia","short_name": "S","events_played": "17","official_total_points": "$3,522,476","tour_wins": "","top_10_finishes": "1","points_behind_lead": "","official_rank": "18","prev_rank": "18","position_change": "8","group": 1,"projected_event_points": "28","projected_rank": "10","projected_total_points": "$2,641,631","projected_sort": 10,"official_sort": 18,"projected_group": 1,"highlight": false},{"pid": "33399","first_name": "Adam","last_name": "Hadwin","short_name": "A","events_played": "28","official_total_points": "$3,455,012","tour_wins": "","top_10_finishes": "1","points_behind_lead": "","official_rank": "19","prev_rank": "19","position_change": "12","group": 1,"projected_event_points": "28","projected_rank": "7","projected_total_points": "$2,779,392","projected_sort": 7,"official_sort": 19,"projected_group": 1,"highlight": false},{"pid": "34098","first_name": "Russell","last_name": "Henley","short_name": "R","events_played": "27","official_total_points": "$3,413,876","tour_wins": "","top_10_finishes": "1","points_behind_lead": "","official_rank": "20","prev_rank": "20","position_change": "5","group": 1,"projected_event_points": "21","projected_rank": "15","projected_total_points": "$2,293,009","projected_sort": 15,"official_sort": 20,"projected_group": 1,"highlight": false},{"pid": "30110","first_name": "Kyle","last_name": "Stanley","short_name": "K","events_played": "29","official_total_points": "$3,402,106","tour_wins": "","top_10_finishes": "1","points_behind_lead": "","official_rank": "21","prev_rank": "21","position_change": "-15","group": 1,"projected_event_points": "135","projected_rank": "36","projected_total_points": "$1,377,135","projected_sort": 36,"official_sort": 21,"projected_group": 2,"highlight": false},{"pid": "25686","first_name": "Jason","last_name": "Dufner","short_name": "J","events_played": "24","official_total_points": "$3,310,341","tour_wins": "","top_10_finishes": "1","points_behind_lead": "","official_
