=== doubleencore/QaTool/sample_schema1/r/r011/stats.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Stats",
    "definitions": {
        "Stats": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "driving_distance": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DrivingAccurat"
                    }
                },
                "driving_distance_avg": {
                    "$ref": "#/definitions/Avg"
                },
                "scoring_average": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DrivingAccurat"
                    }
                },
                "scoring_average_avg": {
                    "$ref": "#/definitions/Avg"
                },
                "gir": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DrivingAccurat"
                    }
                },
                "gir_avg": {
                    "$ref": "#/definitions/Avg"
                },
                "scrambling": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DrivingAccurat"
                    }
                },
                "scrambling_avg": {
                    "$ref": "#/definitions/Avg"
                },
                "driving_accurat": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DrivingAccurat"
                    }
                },
                "driving_accurat_avg": {
                    "$ref": "#/definitions/Avg"
                },
                "strokes_gained_putting": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/DrivingAccurat"
                    }
                },
                "strokes_gained_putting_avg": {
                    "$ref": "#/definitions/Avg"
                }
            },
            "required": [
                "driving_accurat",
                "driving_accurat_avg",
                "driving_distance",
                "driving_distance_avg",
                "gir",
                "gir_avg",
                "scoring_average",
                "scoring_average_avg",
                "scrambling",
                "scrambling_avg",
                "strokes_gained_putting",
                "strokes_gained_putting_avg"
            ],
            "title": "Stats"
        },
        "DrivingAccurat": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "rank": {
                    "type": "string"
                },
                "pid": {
                    "type": "string"
                },
                "score": {
                    "type": "string"
                }
            },
            "required": [
                "pid",
                "rank",
                "score"
            ],
            "title": "DrivingAccurat"
        },
        "Avg": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "average": {
                    "type": "string"
                }
            },
            "required": [
                "average"
            ],
            "title": "Avg"
        }
    }
}

=== doubleencore/QaTool/sample_data/r/r011/stats.json
{"driving_distance": [{"rank": "1","pid": "27141","score": "302.0"},{"rank": "2","pid": "29454","score": "299.8"},{"rank": "3","pid": "32366","score": "299.5"},{"rank": "4","pid": "29289","score": "298.9"},{"rank": "5","pid": "25686","score": "298.1"},{"rank": "6","pid": "35450","score": "297.9"},{"rank": "7","pid": "25900","score": "296.5"},{"rank": "8","pid": "01810","score": "296.3"},{"rank": "9","pid": "30925","score": "296.0"},{"rank": "10","pid": "37455","score": "295.0"},{"rank": "11","pid": "24502","score": "294.8"},{"rank": "12","pid": "30911","score": "294.0"},{"rank": "T13","pid": "26289","score": "293.1"},{"rank": "T13","pid": "29974","score": "293.1"},{"rank": "15","pid": "24024","score": "292.6"},{"rank": "16","pid": "32839","score": "292.5"},{"rank": "17","pid": "30926","score": "292.4"},{"rank": "18","pid": "33141","score": "292.1"},{"rank": "19","pid": "37189","score": "291.9"},{"rank": "20","pid": "31646","score": "291.8"},{"rank": "21","pid": "31557","score": "291.3"},{"rank": "T22","pid": "12716","score": "291.1"},{"rank": "T22","pid": "21209","score": "291.1"},{"rank": "24","pid": "27408","score": "290.9"},{"rank": "T25","pid": "34360","score": "290.1"},{"rank": "T25","pid": "22405","score": "290.1"},{"rank": "T27","pid": "34363","score": "290.0"},{"rank": "T27","pid": "40026","score": "290.0"},{"rank": "29","pid": "30110","score": "289.8"},{"rank": "30","pid": "36689","score": "289.6"},{"rank": "T31","pid": "26908","score": "289.5"},{"rank": "T31","pid": "32102","score": "289.5"},{"rank": "T33","pid": "27644","score": "289.4"},{"rank": "T33","pid": "29478","score": "289.4"},{"rank": "35","pid": "20572","score": "288.8"},{"rank": "36","pid": "26499","score": "288.6"},{"rank": "T37","pid": "24138","score": "288.4"},{"rank": "T37","pid": "29518","score": "288.4"},{"rank": "39","pid": "28237","score": "287.9"},{"rank": "T40","pid": "26329","score": "287.5"},{"rank": "T40","pid": "33413","score": "287.5"},{"rank": "42","pid": "24846","score": "286.4"},{"rank": "43","pid": "35545","score": "286.1"},{"rank": "44","pid": "34098","score": "285.4"},{"rank": "T45","pid": "27349","score": "285.3"},{"rank": "T45","pid": "29221","score": "285.3"},{"rank": "T47","pid": "39954","score": "285.0"},{"rank": "T47","pid": "28089","score": "285.0"},{"rank": "T49","pid": "21528","score": "284.9"},{"rank": "T49","pid": "35506","score": "284.9"},{"rank": "51","pid": "32200","score": "284.3"},{"rank": "52","pid": "25632","score": "284.1"},{"rank": "53","pid": "26758","score": "283.3"},{"rank": "T54","pid": "25198","score": "283.1"},{"rank": "T54","pid": "27974","score": "283.1"},{"rank": "56","pid": "26476","score": "282.6"},{"rank": "57","pid": "25834","score": "282.5"},{"rank": "T58","pid": "31202","score": "282.4"},{"rank": "T58","pid": "33399","score": "282.4"},{"rank": "T58","pid": "22371","score": "282.4"},{"rank": "61","pid": "20396","score": "282.0"},{"rank": "62","pid": "24361","score": "281.9"},{"rank": "63","pid": "25364","score": "281.0"},{"rank": "64","pid": "06567","score": "280.5"},{"rank": "65","pid": "39975","score": "280.1"},{"rank": "66","pid": "46440","score": "278.9"},{"rank": "67","pid": "29222","score": "277.1"},{"rank": "68","pid": "26596","score": "277.0"},{"rank": "69","pid": "33419","score": "275.8"},{"rank": "70","pid": "25572","score": "274.9"},{"rank": "71","pid": "06527","score": "273.9"}],"driving_distance_avg": {"average": "288.8"},"scoring_average": [{"rank": "1","pid": "37455","score": "69.50"},{"rank": "T2","pid": "24138","score": "70.25"},{"rank": "T2","pid": "26329","score": "70.25"},{"rank": "T4","pid": "26499","score": "70.50"},{"rank": "T4","pid": "30110","score": "70.50"},{"rank": "T6","pid": "29518","score": "70.75"},{"rank": "T6","pid": "25900","score": "70.75"},{"rank": "T6","pid": "24502","score": "70.75"},{"rank": "T6","pid": "25198","score": "70.75"},{"rank": "10","pid": "27349","score": "71.00"},{"rank": "11","pid": "31646","score": "71.25"},{"rank": "T12","pid": "30925","score": "71.50"},{"rank": "T12","pid": "46440","score": "71.50"},{"rank": "T12","pid": "30926","score": "71.50"},{"rank": "T12","pid": "29454","score": "71.50"},{"rank": "T16","pid": "35545","score": "71.75"},{"rank": "T16","pid": "06567","score": "71.75"},{"rank": "T16","pid": "29221","score": "71.75"},{"rank": "T16","pid": "21528","score": "71.75"},{"rank": "T16","pid": "35506","score": "71.75"},{"rank": "T16","pid": "36689","score": "71.75"},{"rank": "T22","pid": "32839","score": "72.00"},{"rank": "T22","pid": "34360","score": "72.00"},{"rank": "T22","pid": "25364","score": "72.00"},{"rank": "T22","pid": "29289","score": "72.00"},{"rank": "T22","pid": "26908","score": "72.00"},{"rank": "T22","pid": "31202","score": "72.00"},{"rank": "T22","pid": "24361","score": "72.00"},{"rank": "T22","pid": "35450","score": "72.00"},{"rank": "T30","pid": "33399","score": "72.25"},{"rank": "T30","pid": "27974","score": "72.25"},{"rank": "T30","pid": "12716","score": "72.25"},{"rank": "T30","pid": "33413","score": "72.25"},{"rank": "T30","pid": "21209","score": "72.25"},{"rank": "T35","pid": "37189","score": "72.50"},{"rank": "T35","pid": "31557","score": "72.50"},{"rank": "T35","pid": "33419","score": "72.50"},{"rank": "T35","pid": "32366","score": "72.50"},{"rank": "T35","pid": "34098","score": "72.50"},{"rank": "T35","pid": "28237","score": "72.50"},{"rank": "T41","pid": "01810","score": "72.75"},{"rank": "T41","pid": "22371","score": "72.75"},{"rank": "T41","pid": "29222","score": "72.75"},{"rank": "T41","pid": "30911","score": "72.75"},{"rank": "T41","pid": "34363","score": "72.75"},{"rank": "T41","pid": "06527","score": "72.75"},{"rank": "T41","pid": "27141","score": "72.75"},{"rank": "T48","pid": "20572","score": "73.00"},{"rank": "T48","pid": "26289","score": "73.00"},{"rank": "T48","pid": "29974","score": "73.00"},{"rank": "T48","pid": "39954","score": "73.00"},{"rank": "T48","pid": "24024","score": "73.00"},{"rank": "T53","pid": "26596","score": "73.25"},{"rank": "T53","pid": "25834","score": "73.25"},{"rank": "T53","pid": "27644","score": "73.25"},{"rank": "T56","pid": "26476","score": "73.50"},{"rank": "T56","pid": "29478","score": "73.50"},{"rank": "T56","pid": "32200","score": "73.50"},{"rank": "T56","pid": "25632","score": "73.50"},{"rank": "T60","pid": "25686","score": "73.75"},{"rank": "T60","pid": "39975","score": "73.75"},{"rank": "T60","pid": "33141","score": "73.75"},{"rank": "T60","pid": "32102","score": "73.75"},{"rank": "T60","pid": "28089","score": "73.75"},{"rank": "T65","pid": "20396","score": "74.00"},{"rank": "T65","pid": "24846","score": "74.00"},{"rank": "T65","pid": "40026","score": "74.00"},{"rank": "T65","pid": "22405","score": "74.00"},{"rank": "T69","pid": "26758","score": "74.25"},{"rank": "T69","pid": "27408","score": "74.25"},{"rank": "T69","pid": "25572","score": "74.25"}],"scoring_average_avg": {"average": "73.29"},"gir": [{"rank": "T1","pid": "27349","score": "75.00"},{"rank": "T1","pid": "27974","score": "75.00"},{"rank": "T3","pid": "29454","score": "70.83"},{"rank": "T3","pid": "26476","score": "70.83"},{"rank": "T5","pid": "24138","score": "69.44"},{"rank": "T5","pid": "31646","score": "69.44"},{"rank": "T5","pid": "30925","score": "69.44"},{"rank": "T5","pid": "30926","score": "69.44"},{"rank": "T5","pid": "26908","score": "69.44"},{"rank": "T5","pid": "26289","score": "69.44"},{"rank": "T11","pid": "29518","score": "68.06"},{"rank": "T11","pid": "25900","score": "68.06"},{"rank": "T11","pid": "24502","score": "68.06"},{"rank": "T11","pid": "34360","score": "68.06"},{"rank": "T11","pid": "24361","score": "68.06"},{"rank": "T11","pid": "35450","score": "68.06"},{"rank": "T17","pid": "30110","score": "66.67"},{"rank": "T17","pid": "06567","score": "66.67"},{"rank": "T17","pid": "29221","score": "66.67"},{"rank": "T17","pid": "32839","score": "66.67"},{"rank": "T17","pid": "21209","score": "66.67"},{"rank": "T17","pid": "29974","score": "66.67"},{"rank": "T23","pid": "26329","score": "65.28"},{"rank": "T23","pid": "35545","score": "65.28"},{"rank": "T23","pid": "21528","score": "65.28"},{"rank": "T23","pid": "25364","score": "65.28"},{"rank": "T23","pid": "33399","score": "65.28"},{"rank": "T23","pid": "12716","score": "65.28"},{"rank": "T23","pid": "31557","score": "65.28"},{"rank": "T23","pid": "32366","score": "65.28"},{"rank": "T23","pid": "32102","score": "65.28"},{"rank": "T23","pid": "40026","score": "65.28"},{"rank": "T33","pid": "33413","score": "63.89"},{"rank": "T33","pid": "33419","score": "63.89"},{"rank": "T33","pid": "29222","score": "63.89"},{"rank": "T33","pid": "22405","score": "63.89"},{"rank": "T37","pid": "37455","score": "62.50"},{"rank": "T37","pid": "25198","score": "62.50"},{"rank": "T37","pid": "46440","score": "62.50"},{"rank": "T37","pid": "37189","score": "62.50"},{"rank": "T37","pid": "01810","score": "62.50"},{"rank": "T37","pid": "30911","score": "62.50"},{"rank": "T37","pid": "29478","score": "62.50"},{"rank": "T37","pid": "25632","score": "62.50"},{"rank": "T37","pid": "28089","score": "62.50"},{"rank": "T37","pid": "24846","score": "62.50"},{"rank": "T47","pid": "26499","score": "61.11"},{"rank": "T47","pid": "35506","score": "61.11"},{"rank": "T47","pid": "31202","score": "61.11"},{"rank": "T47","pid": "25686","score": "61.11"},{"rank": "T51","pid": "36689","score": "59.72"},{"rank": "T51","pid": "06527","score": "59.72"},{"rank": "T51","pid": "26596","score": "59.72"},{"rank": "T51","pid": "25834","score": "59.72"},{"rank": "T51","pid": "27644","score": "59.72"},{"rank": "T51","pid": "33141","score": "59.72"},{"rank": "T57","pid": "29289","score": "58.33"},{"rank": "T57","pid": "34363","score": "58.33"},{"rank": "T57","pid": "24024","score": "58.33"},{"rank": "T57","pid": "32200","score": "58.33"},{"rank": "T57","pid": "39975","score": "58.33"},{"rank": "T62","pid": "20572","score": "56.94"},{"rank": "T62","pid": "26758","score": "56.94"},{"rank": "T62","pid": "25572","score": "56.94"},{"rank": "T65","pid": "28237","score": "55.56"
